version: 1.0.{build}
image: Visual Studio 2017
build:
  verbosity: detailed

install:
  - set QTDIR=C:\Qt\5.10.1\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - qmake CloudBuildTest.pro
  - mingw32-make
