trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
      architecture: 'x64'

  - script: |
      python -m pip install aqtinstall
    displayName: 'Install Another Qt installer https://github.com/miurahr/aqtinstall/'

  - script: |
      cd $(Build.BinariesDirectory)
      mkdir Qt
      python -m aqt install --outputdir $(Build.BinariesDirectory)\\Qt 5.10.0 windows desktop win32_mingw53
      python -m aqt tool --outputdir $(Build.BinariesDirectory)\\Qt windows tools_mingw 5.3.0-2 qt.tools.win32_mingw530
    displayName: 'Install Qt 5.10.0'

  - script: |
      set QTDIR=$(Build.BinariesDirectory)\\Qt\\5.10.0\\mingw53_32
      set QTTOOLS=$(Build.BinariesDirectory)\\Qt\\Tools\\mingw530_32
      set PATH=%PATH%;%QTDIR%\\bin;%QTTOOLS%\\bin
      qmake.exe --version
      mingw32-make.exe --version
    displayName: 'Test Qt 5.10.0'

  - script: |
      cd $(Build.SourcesDirectory)
      set QTDIR=$(Build.BinariesDirectory)\\Qt\\5.10.0\\mingw53_32
      set QTTOOLS=$(Build.BinariesDirectory)\\Qt\\Tools\\mingw530_32
      set PATH=%PATH%;%QTDIR%\\bin;%QTTOOLS%\\bin
      qmake.exe CloudBuildTest.pro -spec win32-g++
      mingw32-make.exe qmake_all
      mingw32-make.exe -f Makefile.Release
    displayName: 'Build Project'    
  - task: CopyFiles@2
    inputs:
      contents: |
        $(Build.SourcesDirectory)\\release\\CloudBuildTest.exe
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: CloudBuildTestRelease-$(Build.BuildNumber)
