version: 0.2

env:
  variables:
    QTDIR: C:\Qt\5.10.0\mingw53_32
    QTTOOLS: C:\Qt\Tools\mingw530_32

phases:
  install:
    commands:
      - |
        echo "--- install commands"
  pre_build:
    commands:
      - |
        echo "--- pre_build commands"
  build:
    commands:
      - |
        echo "--- build commands"    
        $env:Path = "$($env:QTDIR)\bin;$($env:QTTOOLS)\bin;$env:Path"
        qmake.exe CloudBuildTest.pro -spec win32-g++
        mingw32-make.exe qmake_all
        mingw32-make.exe -f Makefile.Release

artifacts:
  files:
    - release\CloudBuildTest.exe
