version: 0.2

env:
  variables:
    QTDIR: C:\Qt\5.10.1\mingw53_32
    QTTOOLS: C:\Qt\Tools\mingw530_32
 
phases:
  install:
    commands:
      - echo "--- install commands"
  pre_build:
    commands:
      - echo "--- pre_build commands"
      - $env:Path = "$env:QTDIR\bin;$env:QTTOOLS\bin;C:\MinGW\bin;$env:Path"
      - env
