version: 0.2

env:
  variables:
    QTDIR: C:\Qt\5.10.0\mingw53_32
    QTTOOLS: C:\Qt\Tools\mingw530_32

phases:
  install:
    commands:
      - echo "--- install commands"
  pre_build:
    commands:
      - echo "--- pre_build commands"
      - |
        echo $env:QTDIR
        echo $env:QTTOOLS
        $env:Path = "$($env:QTDIR)\bin;$($env:QTTOOLS)\bin;$env:Path"
        echo $env:Path
        qmake.exe --version
        mingw32-make.exe --version
